import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from '../components/Navbar';
import Script from 'next/script';

export const metadata = {
  title: "FastAPI + NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head />
      <body className="bg-light">
        <Navbar />
        {children}
        <Script
          src="/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
